In [1]:
import tensorflow as tf
import numpy as np

# Let's check the current recommended vesrion of tensorflow
tf.__version__

'2.6.0'

**Creating a Tensor**

In [2]:
# Rank 0Tebsor (scaler)
a = tf.constant(3)
print(a) # "a" is a Rank 0 Tensor (0 dimensional array) of Int32

tf.Tensor(3, shape=(), dtype=int32)


In [5]:
# Rank 1 Tensor
b = tf.constant([1, 2, 3, 4])
print(b) # "b" is a Rank 1 Tensor of Int32

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [6]:
# Rank 2 Tensor
c = tf.constant([[1, 2], [3, 4]])
print(c) # "c" is a Rank 2 Tensor of Int32

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


**Converting Numpy array to Tensor**

In [8]:
array = np.array([1, 2, 3, 4])
print("Before: ", array)
array = tf.convert_to_tensor(array)
print("After: ", array)

Before:  [1 2 3 4]
After:  tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


**Arithmetic operations on Tensor**

In [9]:
# Sample 2D tensor
tensor = tf.constant([[1, 2], [3, 4]])

In [10]:
# Add 1 to all position
tensor = tf.add(tensor, 1)
print("Added 1: ", tensor)

Added 1:  tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [12]:
# sub 1 from all positions
tensor = tf.subtract(tensor, 1)
print("sbtracted 1: ", tensor)

sbtracted 1:  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [13]:
# Div 2 on all positions
tensor = tf.divide(tensor, 2)
print("Divided by 2: ", tensor)

Divided by 2:  tf.Tensor(
[[0.5 1. ]
 [1.5 2. ]], shape=(2, 2), dtype=float64)


In [14]:
# Multiply by 2 all positions
tensor = tf.multiply(tensor, 2)
print("Multiplied by 2: ", tensor)

Multiplied by 2:  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)


In [ ]:
# We can also performed arithmetic operations over vectors

**Matrix** **Multiplication**

In [15]:
tensor = tf.constant([[1, 2], [3, 4]])
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [16]:
tf.multiply(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

**Activations**

In [17]:
tensor = tf.constant([[1, 2], [5, 10]], dtype=tf.float64)
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

In [18]:
# Appling softmax
tf.nn.softmax(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.26894142, 0.73105858],
       [0.00669285, 0.99330715]])>

In [19]:
# Appling relu
tf.nn.relu(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

In [20]:
# Appling leaky relu
tf.nn.leaky_relu(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

In [ ]:
# Tensorflow has all the activation function built in it and ready to be used

**Optimizers**

In [21]:
# Tensorflow has all known Optimizers 
Optimizer = tf.keras.optimizers.Adam()
print(Optimizer) # Refers to Optimizer class created

**Basic Neural Network Structure**

In [22]:
# Start the model with Sequential object
model = tf.keras.models.Sequential()

# Next add in the input object and specify the dimension to pass in
model.add(tf.keras.Input(shape=(10,))) # 10 here represents the number of columns in the data set

# Add in the neurons the first layer
model.add(tf.keras.layers.Dense(32))

# Add 2nd layer
model.add(tf.keras.layers.Dense(16))

# Print summary to understand the neural network flow
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                352       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
Total params: 880
Trainable params: 880
Non-trainable params: 0
_________________________________________________________________
